version: "3.9"
services:
  db:
    image: postgres:latest
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/test_ruby_rails

  web:
    build: 
      context: .
      dockerfile: Procfile.dev
    command: bash -c "./bin/dev"
    tty: true
    volumes:
      - .:/test_ruby_rails
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - sidekiq
    environment:
      - REDIS_URL=redis://redis:6379/0