development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("JOB_WORKER_URL") { "redis://localhost:6379/0" } %>
  channel_prefix: test_ruby_rails_production
